productFields:
- id: product_documents
  type: MultiField
  name:
    sv-SE: Produkt dokument
  description:
    sv-SE: 'Produktblad '
  settings:
    multiCulture: false
    administration:
      columns: false
      filter: false
      readonly: false
    storefront:
      visible: true
      searchable: true
  option:
    fields:
    - product_document
    isArray: true
