productFields:
- id: product_tags_from_date
  type: DateTime
  settings:
    multiCulture: false
    administration:
      columns: true
      filter: true
      readonly: false
    storefront:
      visible: true
      searchable: true
