websiteFields:
- id: ProductListPointer
  type: Pointer
  name:
    en-US: Product list pointer
    sv-SE: Produktuppsättning pekare
  description:
    en-US: The product list pointer
    sv-SE: Produktens pekare
  settings:
    multiCulture: false
    administration:
      columns: false
      filter: false
      readonly: false
    storefront:
      visible: true
      searchable: true
  option:
    entityType: ProductsProductList
