productTemplates:
- type: Product
  productFieldGroups:
  - id: General
    fields:
    - id: _name
    - id: product_tags
    - id: product_status
    - id: product_reference
    - id: product_family
    - id: product_category_reference
    - id: product_bullets
    - id: product_brand
    - id: Brand
    - id: Type
    - id: Color
    - id: Size
    administration:
      collapsed: false
    storefront:
      visible: false
  - id: Description
    name:
      sv-SE: Beskrivning
    fields:
    - id: _description
    administration:
      collapsed: false
    storefront:
      visible: true
  - id: Product information
    name:
      en-US: Product information
      sv-SE: Teknisk specifikation
    administration:
      collapsed: false
    storefront:
      visible: true
  - id: Documents
    name:
      sv-SE: Dokument
    administration:
      collapsed: true
    storefront:
      visible: true
  - id: Reviews
    name:
      sv-SE: 'Recensioner '
    administration:
      collapsed: true
    storefront:
      visible: true
  - id: Brand
    name:
      sv-SE: Om varumärket
    fields:
    - id: product_brand
    administration:
      collapsed: true
    storefront:
      visible: true
  variantFieldGroups:
  - id: General
    fields:
    - id: _name
    - id: _description
    - id: _url
    - id: _seoTitle
    - id: _seoDescription
    - id: article_vat
    - id: article_tags
    - id: article_show_supplier_art_nr
    - id: article_supplier_art_nr
    - id: article_status_erp
    - id: article_status
    - id: article_reference
    - id: article_product_reference
    - id: article_name
    - id: article_ean
    - id: article_approved
    administration:
      collapsed: false
    storefront:
      visible: false
  - id: Product information
    name:
      en-US: Product information
      sv-SE: Teknisk specifikation
    fields:
    - id: article_weight_kg
    - id: article_size
    - id: article_model
    - id: article_length
    - id: article_height
    - id: article_diameter
    - id: article_detail
    - id: article_color
    administration:
      collapsed: false
    storefront:
      visible: true
  useVariantUrl: true
  settings:
    grouping: article_weight_kg
  id: ProductWithVariants
  name:
    en-US: Product with variants (weight kg)
    sv-SE: Produkt med varianter
